CREATE DATABASE jobbot;

CREATE TABLE jobs(
	id VARCHAR(255) PRIMARY KEY NOT NULL,
	title VARCHAR(255) NOT NULL, 
	company VARCHAR(255) NOT NULL, 
	clocation VARCHAR(255) NOT NULL, 
	link VARCHAR(255) NOT NULL, 
	createdat VARCHAR(255) NOT NULL
);